# Generated by Django 5.2 on 2025-06-23 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=255)),
                (
                    "no_hp",
                    models.CharField(blank=True, max_length=14, null=True, unique=True),
                ),
                ("alamat", models.TextField(blank=True, null=True)),
                (
                    "foto_profile",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("regular", "Regular User")],
                        default="regular",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="Testimoni",
            fields=[
                ("testimoni_id", models.AutoField(primary_key=True, serialize=False)),
                ("testi_text", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "testimonies",
            },
        ),
        migrations.CreateModel(
            name="TestimoniImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.ImageField(upload_to="testimoni_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "testimoni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="temuapp.testimoni",
                    ),
                ),
            ],
            options={
                "db_table": "testimoni_images",
            },
        ),
        migrations.CreateModel(
            name="TouristSpot",
            fields=[
                ("spot_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("address", models.TextField()),
                ("kota", models.TextField()),
                ("kecamatan", models.TextField()),
                ("desa", models.TextField()),
                ("fasilitas", models.TextField()),
                (
                    "google_maps_url",
                    models.URLField(blank=True, max_length=255, null=True),
                ),
                ("category", models.CharField(max_length=100)),
                (
                    "price_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_max",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("is_reported", models.BooleanField(default=False)),
                ("is_removed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_spots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tourist_spots",
            },
        ),
        migrations.AddField(
            model_name="testimoni",
            name="spot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testimonies",
                to="temuapp.touristspot",
            ),
        ),
        migrations.CreateModel(
            name="SpotImage",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("file_name", models.ImageField(upload_to="spot_images/")),
                ("is_primary", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spot_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="temuapp.touristspot",
                    ),
                ),
            ],
            options={
                "db_table": "spot_images",
            },
        ),
        migrations.CreateModel(
            name="FavoriteSpot",
            fields=[
                ("favorite_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_spots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="temuapp.touristspot",
                    ),
                ),
            ],
            options={
                "db_table": "favorite_spots",
                "unique_together": {("user", "spot")},
            },
        ),
    ]
