# Generated by Django 5.2 on 2025-05-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
    ]
