# Generated by Django 5.2 on 2025-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0002_remove_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="alamat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="foto_profile",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="no_hp",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
    ]
