# Generated by Django 5.2 on 2025-05-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0003_alter_user_alamat_alter_user_foto_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristspot",
            name="category",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
