# Generated by Django 5.2 on 2025-05-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0004_alter_touristspot_category_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="touristspot",
            name="category",
            field=models.CharField(max_length=100),
        ),
    ]
