# Generated by Django 5.2 on 2025-05-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0005_alter_touristspot_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristspot",
            name="fasilitas",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="touristspot",
            name="google_maps_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
