# Generated by Django 5.2 on 2025-05-29 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0006_touristspot_fasilitas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="touristspot",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="touristspot",
            name="is_reported",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ReportTouristSpot",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("resolved", "Resolved")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("admin_action", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spot_reports_made",
                        to="temuapp.user",
                    ),
                ),
                (
                    "spot_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="temuapp.touristspot",
                    ),
                ),
            ],
            options={
                "db_table": "report_tourist_spots",
            },
        ),
    ]
