# Generated by Django 5.2.1 on 2025-06-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0007_touristspot_is_removed_touristspot_is_reported_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="touristspot",
            old_name="price",
            new_name="price_max",
        ),
        migrations.AddField(
            model_name="touristspot",
            name="price_min",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
