# Generated by Django 5.2.1 on 2025-06-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0009_rename_password_hash_user_password_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewimage",
            name="file_name",
            field=models.ImageField(upload_to="review_images/"),
        ),
        migrations.AlterField(
            model_name="spotimage",
            name="file_name",
            field=models.ImageField(upload_to="spot_images/"),
        ),
    ]
