# Generated by Django 5.2.1 on 2025-06-11 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0010_alter_reviewimage_file_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteSpot",
            fields=[
                ("favorite_id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "spot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="temuapp.touristspot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_spots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "favorite_spots",
                "unique_together": {("user", "spot")},
            },
        ),
    ]
