# Generated by Django 5.2.1 on 2025-06-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("temuapp", "0011_favoritespot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="foto_profile",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
